/**
 * Translation key union, generated by TypeScript from the English namespace files (English is the source of truth).
 * Adding a namespace: create locales/<lang>/<ns>.json for every language and add one `import type` + union member here.
 */
import type core from './en/core.json';
import type planner from './en/planner.json';
import type background from './en/background.json';
import type studio from './en/studio.json';
import type studioVoice from './en/studio.voice.json';
import type studioIdeas from './en/studio.ideas.json';
import type studioInbox from './en/studio.inbox.json';

export type Key =
  | keyof typeof core
  | keyof typeof planner
  | keyof typeof background
  | keyof typeof studio
  | keyof typeof studioVoice
  | keyof typeof studioIdeas
  | keyof typeof studioInbox;
