/**
 * Translation key union, generated by TypeScript from the English namespace files (English is the source of truth).
 * Adding a namespace: create locales/<lang>/<ns>.json for every language and add one `import type` + union member here.
 */
import type core from './en/core.json';
import type planner from './en/planner.json';
import type background from './en/background.json';
import type studio from './en/studio.json';
import type studioVoice from './en/studio.voice.json';
import type studioIdeas from './en/studio.ideas.json';
import type studioInbox from './en/studio.inbox.json';
// v2.0 feature namespaces (chunk B stubs; each chunk fills only its own file)
import type youtube from './en/youtube.json';
import type tiktok from './en/tiktok.json';
import type inbox from './en/inbox.json';
import type worker from './en/worker.json';
import type team from './en/team.json';
import type cli from './en/cli.json';
import type providers from './en/providers.json';

export type Key =
  | keyof typeof core
  | keyof typeof planner
  | keyof typeof background
  | keyof typeof studio
  | keyof typeof studioVoice
  | keyof typeof studioIdeas
  | keyof typeof studioInbox
  | keyof typeof youtube
  | keyof typeof tiktok
  | keyof typeof inbox
  | keyof typeof worker
  | keyof typeof team
  | keyof typeof cli
  | keyof typeof providers;
